"""Command-line interface for autoconfig."""

from __future__ import annotations

import importlib
import importlib.util
import sys
from pathlib import Path
from typing import Annotated

import typer

from .models import ConfigurationDefinition
from .formats import normalize_format
from .service import ConfigFileExistsError, ConfigMaker

app = typer.Typer(help="Generate and validate declarative Python configurations.")


_INIT_DEFINITION = '''"""Starter configuration generated by autoconfig init."""

from autoconfig import ConfigurationDefinition, ConfigurationSection, config_field


class Server(ConfigurationSection):
    """A server entry. Add or remove fields to fit your application."""

    host: str = config_field("localhost", description="Server hostname")
    port: int = config_field(8080, description="Server port")
    debug: bool = config_field(False, description="Enable debug mode")


class AppConfig(ConfigurationDefinition):
    """Application configuration."""

    servers: list[Server] = config_field(description="Configured server entries")
'''


def _definition(
    spec: str,
    search_path: Path | None = None,
) -> type[ConfigurationDefinition]:
    """Import a configuration definition from ``module:Class``.

    ``search_path`` is added to ``sys.path`` so definitions stored beside the
    configuration files work when the installed console script is launched
    from another directory.
    """
    if search_path is not None:
        resolved_search_path = str(search_path.resolve())
        if resolved_search_path not in sys.path:
            sys.path.insert(0, resolved_search_path)
    try:
        module_name, class_name = spec.split(":", 1)
        value = getattr(importlib.import_module(module_name), class_name)
    except (ValueError, ImportError, AttributeError) as exc:
        raise typer.BadParameter("Definition must use the form module:Class") from exc
    if not isinstance(value, type) or not issubclass(value, ConfigurationDefinition):
        raise typer.BadParameter("Definition must inherit from ConfigurationDefinition")
    return value


def _definition_from_file(path: Path, class_name: str = "AppConfig") -> type[ConfigurationDefinition]:
    module_name = f"autoconfig_init_{path.stem}"
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise typer.BadParameter(f"Unable to import definition file: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    value = getattr(module, class_name, None)
    if not isinstance(value, type) or not issubclass(value, ConfigurationDefinition):
        raise typer.BadParameter(
            f"Definition file must expose {class_name}, inheriting from ConfigurationDefinition"
        )
    return value


@app.command()
def generate(
    definition: Annotated[str, typer.Option("--definition", "-d", help="Python definition as module:Class.")],
    directory: Annotated[Path, typer.Option("--directory", "-o")] = Path("."),
    environment: Annotated[str | None, typer.Option("--environment", "-e")] = None,
    format_name: Annotated[str, typer.Option("--format", "-f")] = "toml",
    recreate: Annotated[bool, typer.Option("--recreate", help="Replace an existing file.")] = False,
    uncommented: Annotated[bool, typer.Option("--uncommented", help="Generate without comments or metadata.")] = False,
) -> None:
    """Generate a configuration template from an importable definition."""
    try:
        path = ConfigMaker(_definition(definition, directory), directory).generate(
            environment=environment,
            format_name=format_name,
            recreate=recreate,
            uncommented=uncommented,
        )
    except ConfigFileExistsError as exc:
        typer.echo(f"Error: {exc}", err=True)
        raise typer.Exit(code=1) from None
    typer.echo(f"Generated {path}")


@app.command()
def validate(
    definition: Annotated[str, typer.Option("--definition", "-d")],
    directory: Annotated[Path, typer.Option("--directory", "-o")] = Path("."),
    environment: Annotated[str | None, typer.Option("--environment", "-e")] = None,
    format_name: Annotated[str, typer.Option("--format", "-f")] = "toml",
) -> None:
    """Validate the configuration files for an importable definition."""
    ConfigMaker(_definition(definition, directory), directory).load(
        environment=environment,
        format_name=format_name,
    )
    typer.echo("Configuration is valid")


@app.command()
def init(
    directory: Annotated[Path, typer.Option("--directory", "-o", help="Directory to initialize.")] = Path("."),
    definition_file: Annotated[
        Path,
        typer.Option("--definition-file", help="Python file to create.")
    ] = Path("config_definition.py"),
    format_name: Annotated[str, typer.Option("--format", "-f", help="Configuration format.")] = "toml",
    recreate: Annotated[bool, typer.Option("--recreate", help="Replace generated files.")] = False,
) -> None:
    """Create a starter Python definition and its configuration template."""
    directory = directory.resolve()
    target = definition_file if definition_file.is_absolute() else directory / definition_file
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists() and not recreate:
        typer.echo(f"Error: definition file already exists: {target}. Use --recreate to replace it.", err=True)
        raise typer.Exit(code=1)

    normalized_format = normalize_format(format_name)
    config_path = directory / f"config.{normalized_format}"
    if config_path.exists() and not recreate:
        typer.echo(f"Error: configuration file already exists: {config_path}. Use --recreate to replace it.", err=True)
        raise typer.Exit(code=1)

    target.write_text(_INIT_DEFINITION, encoding="utf-8")
    definition = _definition_from_file(target)
    path = ConfigMaker(definition, directory).generate(
        format_name=format_name,
        recreate=recreate,
    )
    typer.echo(f"Created {target}")
    typer.echo(f"Generated {path}")


if __name__ == "__main__":
    app()
