import {
  lucideActivity,
  lucideAlertCircle,
  lucideArrowLeft,
  lucideArrowDown,
  lucideArrowRight,
  lucideArrowUpRight,
  lucideBoxes,
  lucideCalendarDays,
  lucideCamera,
  lucideCheck,
  lucideCheckCircle2,
  lucideClock3,
  lucideFactory,
  lucideMapPin,
  lucideMinus,
  lucideMenu,
  lucidePackage,
  lucidePackagePlus,
  lucidePlus,
  lucideQrCode,
  lucideScanLine,
  lucideSearch,
  lucideShoppingCart,
  lucideSun,
  lucideUserRound,
  lucideWrench,
} from '@ng-icons/lucide';

export const UI_ICON_SET = {
  lucideActivity,
  lucideAlertCircle,
  lucideArrowLeft,
  lucideArrowDown,
  lucideArrowRight,
  lucideArrowUpRight,
  lucideBoxes,
  lucideCalendarDays,
  lucideCamera,
  lucideCheck,
  lucideCheckCircle2,
  lucideClock3,
  lucideFactory,
  lucideMapPin,
  lucideMinus,
  lucideMenu,
  lucidePackage,
  lucidePackagePlus,
  lucidePlus,
  lucideQrCode,
  lucideScanLine,
  lucideSearch,
  lucideShoppingCart,
  lucideSun,
  lucideUserRound,
  lucideWrench,
} as const;

export const UI_ICON_NAMES = {
  activity: 'lucideActivity',
  alert: 'lucideAlertCircle',
  arrowLeft: 'lucideArrowLeft',
  arrowDown: 'lucideArrowDown',
  arrowRight: 'lucideArrowRight',
  arrowUpRight: 'lucideArrowUpRight',
  boxes: 'lucideBoxes',
  calendar: 'lucideCalendarDays',
  camera: 'lucideCamera',
  check: 'lucideCheck',
  checkCircle: 'lucideCheckCircle2',
  clock: 'lucideClock3',
  factory: 'lucideFactory',
  location: 'lucideMapPin',
  minus: 'lucideMinus',
  menu: 'lucideMenu',
  package: 'lucidePackage',
  packagePlus: 'lucidePackagePlus',
  plus: 'lucidePlus',
  qrCode: 'lucideQrCode',
  scan: 'lucideScanLine',
  search: 'lucideSearch',
  shoppingCart: 'lucideShoppingCart',
  sun: 'lucideSun',
  user: 'lucideUserRound',
  wrench: 'lucideWrench',
} as const;

export type UiIconName = keyof typeof UI_ICON_NAMES;
